---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: aws-granted
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/mokhtarjr74/aws-granted.git
