---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: django-kustomization
  namespace: flux-system
spec:
  interval: 30s
  path: ./clusters/my-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: aws-granted
  targetNamespace: django-app
